name: directus_api_manager
description: Communicate with a Directus server using its REST API.
version: 1.2.1

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
