name: directus_api_manager
description: Communicate with a Directus server using its REST API.
version: 1.2.1

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  http: ^0.13.4
  reflectable: ^4.0.5

dev_dependencies:
  build_runner: any
  lints: ^2.0.1
  test: ^1.16.0


targets:
  $default:
    builders:
      reflectable:
        generate_for:
          - example/directus_api_manager_example.dart
        options:
          formatted: true